USE [master]
GO

/****** Object:  Database [DevShops]    Script Date: 4/10/2021 2:53:53 PM ******/
DROP DATABASE [DevShops]
GO

/****** Object:  Database [DevShops]    Script Date: 4/10/2021 2:53:53 PM ******/
CREATE DATABASE [DevShops]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DevShops', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DevShops.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DevShops_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DevShops_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DevShops].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DevShops] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DevShops] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DevShops] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DevShops] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DevShops] SET ARITHABORT OFF 
GO

ALTER DATABASE [DevShops] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DevShops] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DevShops] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DevShops] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DevShops] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DevShops] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DevShops] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DevShops] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DevShops] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DevShops] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DevShops] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DevShops] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DevShops] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DevShops] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DevShops] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DevShops] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DevShops] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DevShops] SET RECOVERY FULL 
GO

ALTER DATABASE [DevShops] SET  MULTI_USER 
GO

ALTER DATABASE [DevShops] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DevShops] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DevShops] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DevShops] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DevShops] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DevShops] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DevShops] SET  READ_WRITE 
GO

