version: '3.9'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports: 
      - 1434:1433
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=UsRSQL#PV
    volumes:
      - /var/opt/mssql

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:80'
    depends_on:
      - mssql




