version: '3.9'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports: 
      - 1433:1433
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=UsRSQL#PV
    volumes:
      - mssql-data:/var/opt/mssql/
  
  dbup:
    build:
      context: DevShop-Backend/DbUp/
      dockerfile: Dockerfile
    depends_on:
      - webapi
    entrypoint: ["/wait-for-it.sh", "webapi:80", "-t", "120", "--", "dotnet", "DbUp.dll"]
    environment:
      connectionString: "Data Source=mssql;Initial Catalog=DevShops;User Id=SA;Password=UsRSQL#PV;"

  webapi:
    build:
      context: DevShop-Backend/
      dockerfile: Dockerfile
    ports:
      - '5000:80'
    depends_on:
      - mssql
    entrypoint: ["/wait-for-it.sh", "mssql:1433", "-t", "120", "--", "dotnet", "devshops.Api.dll"]

  seq:
    image: datalust/seq
    ports:
      - 5341:80
    depends_on:
      - dbup
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/seq-data

volumes:
  mssql-data: 
  seq-data:




